### ISSUE TITLE
Backend not starting on Windows 10

### ISSUE THREAD

**Issue by lstyp** [hoerlteam/YeastMate#4]
Hello,

I've tried to do as much as I can with my limited knowledge of computing/programming.

I've tried to start the backends in several ways, and nothing is working. 

What happens is that two windows open, something starts to run and then the two command line windows close.

I've tried re-installing in different folders, etc.

Any help would be greatly appreciated!

Thanks in advance.

**Comment by ravenbunk** [comment]
Hi @lstyp 

thanks for trying out YeastMate!

The most common issue with crashing backends are missing dependencies - in case of Windows 10 that would be the Microsoft Visual C++ libraries, which sometimes are missing on some systems.

There's download links (to the official Microsoft site) in our docs @ https://yeastmate.readthedocs.io/en/latest/gui/ .

In case you already tried this or it didn't help, I would need some more output from the crashing backends, which can be generated as follows:

Open a terminal window (Win+R keys, then type cmd.exe), then navigate to the YeastMate installation folder (cd PATH/TO/YEASTMATE). There should be a subfolder called python (it might be in another subfolder, I'm on MacOS right now and can't check how it is on Windows) with another folder called YeastMate. There you can find the 2 backend .exe files called hueyserver.exe and yeastmate_server.exe

After navigating again in to this subfolder, you can then execute these files in your terminal window by writing the filenames. This time the terminal windows will keep open (because it was manually created beforehand) and there should be some output now, detailling the error why these crashed.

If you can post me this output, I will take a look and find out what's going on and come back to you.
If you need more help in getting the backends to start in the terminal, I'm happy to help as well.

Thanks!

**Comment by lstyp** [comment]
Hi @davidbunk 

Thanks for your reply. 

I installed the Microsoft libraries but keep getting the same error. Maybe I'm missing something during the install (looks like it but not sure what).

These are the output logs from the command line:

Traceback (most recent call last):
  File "hueyserver.py", line 15, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "tasks.py", line 15, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "alignment.py", line 10, in <module>
  File "C:\Users\tafurpet\Documents\YeastMate\resources\python\YeastMate\cv2\__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: DLL load failed while importing cv2: The specified module could not be found.
[15004] Failed to execute script 'hueyserver' due to unhandled exception!

Traceback (most recent call last):
  File "yeastmate_server.py", line 22, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "yeastmatedetector\inference.py", line 10, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "detectron2\__init__.py", line 5, in <module>
    setup_environment()
  File "detectron2\utils\env.py", line 108, in setup_environment
    _configure_libraries()
  File "detectron2\utils\env.py", line 72, in _configure_libraries
    import cv2
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "cv2\__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: DLL load failed while importing cv2: The specified module could not be found.
[12188] Failed to execute script 'yeastmate_server' due to unhandled exception!

Thanks a lot for your help!

**Comment by ravenbunk** [comment]
Hi @lstyp ,

thanks for your logs. I did some more debugging over the weekend, and found a major issue with the help of your output logs that would affect a lot of systems, and I'm hopeful that this is also the reason why the backends are failing on your system.

Do you happen to use a Windows 10 **N** version? It is (as far as I know) only distributed in some European countries, but is also missing some relevant dependencies for working with images/videos because of EU guidelines. You can check this by going into the System Properties (the shortcut for this is Win + Pause keys). 

Unfortunately, even though I'm in the EU myself, I only tested everything on the international versions, and thus it slipped past me.

If this is the case, you can install the missing Windows parts from [the official Microsoft site](https://www.microsoft.com/en-us/software-download/mediafeaturepack).

**Comment by ravenbunk** [comment]
Hi @lstyp ,

did this solve your issue? If so, I will close this issue soon.

**Comment by lstyp** [comment]
Hi @davidbunk 

Sorry for the lack of feedback. That indeed solved the backend issue.

Thanks!
